import json
import os

DB_FILE = "latest_state.json"

def save_cycle_result(data):
    """Saves the output generated by run_clara_cycle()."""
    with open(DB_FILE, "w") as f:
        json.dump(data, f, indent=2)

def load_saved_state():
    """Reads saved state for GET endpoints without triggering the AI cycle."""
    if not os.path.exists(DB_FILE):
        return {
            "state": "OBSERVING",
            "topics": [],
            "feed": [],
            "memory": []
        }
    try:
        with open(DB_FILE, "r") as f:
            return json.load(f)
    except Exception:
        return {
            "state": "OBSERVING",
            "topics": [],
            "feed": [],
            "memory": []
        }