import json
import os
from typing import Any, Dict, List

from ai_engine.persona import CLARA_PERSONA


def _safe_json_loads(text: str) -> Dict[str, Any]:
    """
    Tries to parse JSON even if the model wraps it in markdown fences.
    """

    text = text.strip()

    if text.startswith("```"):
        text = text.replace("```json", "").replace("```", "").strip()

    try:
        return json.loads(text)

    except Exception:
        return {
            "post_text": text,
            "rationale": "Generated by Clara from the selected story.",
            "topic": "AI / Technology",
            "entities": [],
            "main_claim": text[:180],
            "angle": "Consequence over hype",
            "stance": "Analytical",
            "belief_updates": [],
        }


def _build_prompt(
    story: Dict[str, Any],
    related_memories: List[Dict[str, Any]],
    beliefs: List[Dict[str, Any]],
) -> str:
    memory_text = json.dumps(
        related_memories[:3],
        indent=2,
        ensure_ascii=False,
    )

    belief_text = json.dumps(
        beliefs,
        indent=2,
        ensure_ascii=False,
    )

    persona_text = json.dumps(
        CLARA_PERSONA,
        indent=2,
        ensure_ascii=False,
    )

    story_text = json.dumps(
        story,
        indent=2,
        ensure_ascii=False,
    )

    return f"""
You are Clara Voss, an autonomous AI Systems Analyst.

Your editorial philosophy is:
"Novelty isn't news. Consequence is."

You do NOT write generic AI news summaries.
You identify what materially changes the AI ecosystem and explain why.

PERSONA:
{persona_text}

SELECTED STORY:
{story_text}

RELATED EDITORIAL MEMORIES:
{memory_text}

CURRENT BELIEFS:
{belief_text}

Your task is to produce ONE concise editorial post.

Requirements:
- 90 to 180 words.
- Sharp, analytical, composed.
- No clickbait.
- No generic hype.
- No "Here are 5 things".
- Do not sound like a marketing bot.
- Focus on consequence, not announcement.
- If memory is relevant, advance the previous argument rather than repeating it.
- Mention uncertainty when appropriate.
- Do not invent facts beyond the supplied story.
- The first line should feel like a strong editorial observation.
- The post should feel like an intelligent human analyst wrote it.

Also produce a strong rationale explaining:
- why this story was worth publishing
- why it matters now
- why it fits Clara's editorial identity
- how it differs from previous coverage if memory exists

Return ONLY valid JSON in this exact shape:

{{
  "post_text": "...",
  "rationale": "...",
  "topic": "...",
  "entities": ["...", "..."],
  "main_claim": "...",
  "angle": "...",
  "stance": "...",
  "belief_updates": [
    {{
      "belief_id": "...",
      "effect": "STRENGTHENED | CHALLENGED | STABLE",
      "reason": "..."
    }}
  ]
}}
"""


def generate_with_groq(
    story: Dict[str, Any],
    related_memories: List[Dict[str, Any]],
    beliefs: List[Dict[str, Any]],
) -> Dict[str, Any]:
    try:
        from groq import Groq

    except ImportError:
        raise RuntimeError(
            "Groq package not installed. Run: pip install groq"
        )

    api_key = os.getenv("GROQ_API_KEY")

    if not api_key:
        raise RuntimeError(
            "Missing GROQ_API_KEY environment variable."
        )

    client = Groq(api_key=api_key)

    prompt = _build_prompt(
        story=story,
        related_memories=related_memories,
        beliefs=beliefs,
    )

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": (
                    "You are Clara Voss, a rigorous autonomous AI technology editor. "
                    "Return only valid JSON."
                ),
            },
            {
                "role": "user",
                "content": prompt,
            },
        ],
        temperature=0.55,
        max_tokens=900,
    )

    content = response.choices[0].message.content

    return _safe_json_loads(content)


def generate_mock_post(
    story: Dict[str, Any],
    related_memories: List[Dict[str, Any]],
    beliefs: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """
    Fallback so the pipeline still works even if no LLM key is configured.
    """

    title = story.get("title", "AI development")

    return {
        "post_text": (
            f"{title} is interesting for a reason that has less to do with the headline "
            f"and more to do with what it changes downstream. "
            f"The important question is whether this alters capability, cost, access, "
            f"or the way autonomous systems are actually deployed. "
            f"If it does, it deserves attention. If it doesn't, it is probably noise."
        ),

        "rationale": (
            "Selected because the story cleared Clara's editorial threshold and "
            "appears relevant to her focus on consequential AI systems developments."
        ),

        "topic": story.get("category", "AI / Technology"),

        "entities": [],

        "main_claim": (
            "The consequence of the development matters more than the announcement itself."
        ),

        "angle": "Consequence over announcement",

        "stance": "Analytical and skeptical",

        "belief_updates": [],
    }


def generate_post(
    story: Dict[str, Any],
    related_memories: List[Dict[str, Any]] = None,
    beliefs: List[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    related_memories = related_memories or []
    beliefs = beliefs or []

    provider = os.getenv(
        "CLARA_LLM_PROVIDER",
        "groq",
    ).lower()

    try:
        if provider == "groq":
            return generate_with_groq(
                story,
                related_memories,
                beliefs,
            )

    except Exception as exc:
        print(f"[Writer] LLM generation failed: {exc}")
        print("[Writer] Falling back to mock generation.")

    return generate_mock_post(
        story,
        related_memories,
        beliefs,
    )